"""add deleted_at field for soft delete

Revision ID: 2309ee286fa1
Revises: c68e5199756e
Create Date: 2026-09-24 11:44:01.944567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2309ee286fa1'
down_revision: Union[str, None] = 'c68e5199756e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawler_configs', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（逻辑删除）'))
    op.create_index('idx_deleted_at', 'crawler_configs', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deleted_at', table_name='crawler_configs')
    op.drop_column('crawler_configs', 'deleted_at')
    # ### end Alembic commands ###
